BUILD_BIN := $(BUILD_DIR)/bin
BUILD_LIB := $(BUILD_DIR)/lib
BUILD_FUNC := $(BUILD_DIR)/func
BUILD_EMACS := $(BUILD_DIR)/emacs/lisp
BUILD_DOT := $(BUILD_DIR)/dot

INSTALL_DIR := ${HOME}
INSTALL_BIN := $(INSTALL_DIR)/bin
INSTALL_LIB := $(INSTALL_DIR)/lib
INSTALL_FUNC := $(INSTALL_DIR)/.func
INSTALL_EMACS := $(INSTALL_DIR)/emacs/lisp
INSTALL_DOT := $(INSTALL_DIR)
